# Generated by Django 2.2.24 on 2025-03-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_bulding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='new_bulding',
            new_name='new_building',
        ),
    ]
