# Generated by Django 2.2.24 on 2025-04-12 17:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20250412_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='onwer_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
