# Generated by Django 2.2.24 on 2025-04-13 06:24

from django.db import migrations
import phonenumbers

def edit_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for number in Flat.objects.iterator():
        phone = number.owners_phonenumber
        if phone and phone.strip():
            try:
                parsed_number = phonenumbers.parse(phone, 'RU')
                if phonenumbers.is_valid_number(parsed_number):
                    formatted_number = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
                    number.owner_pure_phone = formatted_number
                    number.save()
            except phonenumbers.NumberParseException:
                print(f"Ошибка парсинга номера: {phone}")  # Отладка ошибок
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250412_2129'),
    ]

    operations = [migrations.RunPython(edit_numbers,reverse_code=migrations.RunPython.noop)
    ]
