# Generated by Django 2.2.24 on 2025-04-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20250413_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='onwer_pure_phone',
            new_name='owner_pure_phone',
        ),
    ]
