# Generated by Django 2.2.24 on 2025-04-18 07:35

from django.db import migrations


def transfer_to_owner(apps, schema_editor):
    Flats = apps.get_model('property','Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flats.objects.iterator():
        name = flat.owner_deprecated
        owners_phonenumber = flat.owners_phonenumber
        owner_pure_phone = flat.owner_pure_phone
        Owner.objects.get_or_create(owner=name, owners_phonenumber=owners_phonenumber, owner_pure_phone=owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20250415_1129'),
    ]

    operations = [migrations.RunPython(transfer_to_owner)
    ]
