# Generated by Django 2.2.24 on 2025-04-18 16:30

from django.db import migrations

def link_flat_owner(apps, schema_editor):
    Flat = apps.get_model('property','Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.iterator():
        flats = Flat.objects.filter(owner_deprecated=owner.name,owner_pure_phone=owner.owner_pure_phone)
        owner.flat.set(flats)

def reverse_link_flat_owner(apps, schema_editor):

    Owner = apps.get_model("property", "Owner")

    for owner in Owner.objects.all():
        owner.flat.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20250418_2013'),
    ]

    operations = [migrations.RunPython(link_flat_owner,
                                       reverse_link_flat_owner)
    ]
